p_portal:
  target: default
  outputs:
    default:
      type: duckdb
      path: ":memory:"
      database: p_portal
      schema: main
      threads: 1
      extensions:
        - httpfs
        - ducklake
      settings:
        s3_url_style: path
        s3_access_key_id: "{{ env_var('FDL_S3_ACCESS_KEY_ID', '') }}"
        s3_secret_access_key: "{{ env_var('FDL_S3_SECRET_ACCESS_KEY', '') }}"
        s3_endpoint: "{{ env_var('FDL_S3_ENDPOINT_HOST', '') }}"
        s3_region: auto
      attach:
        - path: "ducklake:{{ env_var('FDL_CATALOG_PATH', '') }}"
          alias: p_portal
          is_ducklake: true
          options:
            DATA_PATH: "{{ env_var('FDL_DATA_URL', '') }}"
            OVERRIDE_DATA_PATH: true
            META_TYPE: "'sqlite'"
